### ISSUE TITLE
do not work

### ISSUE THREAD

**Issue by timur01061984** [bachagas/Kalman#1]
Hi. I want to use your library for bmp180 pressure sensor, but library do not work.

**Comment by bachagas** [comment]
Really?
What are you trying to do?
What is happening?
If you can, send me a little more detail.
Regards,

**Comment by timur01061984** [comment]
i'm sorry. I't work. I'm not professional programmer and your guide is very abstruse for beginners. Can you add in your article some picture and really work program? Below is result of work filter) Sorry for my English.
![default](https://cloud.githubusercontent.com/assets/11150456/6322154/91a63b42-bb30-11e4-97a7-ebbb189f4018.JPG)

And sketch

#include <Kalman.h>
#include <Wire.h>
#include <Adafruit_BMP085.h>

Adafruit_BMP085 bmp;

double measurement, filteredMeasurement;
Kalman myFilter(0.125,40,1023,0); 
void setup() {
 Serial.begin(9600);
  bmp.begin();
}
void loop() {

```
measurement = (double) bmp.readAltitude(); //read new value from sensor in analog pin A1, for example
filteredMeasurement = myFilter.getFilteredValue(measurement);

Serial.print(measurement);
Serial.print(",");
Serial.println(filteredMeasurement);
```

}

Thank you. Good work.

**Comment by bachagas** [comment]
Hello,
It's hard to tell what the problem is from what you said, but maybe you are facing some issue with the scale and range of the your data values.
The example and initial parameters are based on the usual "raw" analog input read from Arduino, which goes from 0 to 1023, and also I have only used the library with this kind of input.
The function "bmp.readAltitude()" may be returning values which are very apart from that, and this may be causing problems.
For example, you can try to change the filter parameters to see what happens. From what I can figure out about what you are trying to do, I would suggest you use p=0 and 400 for the initial value, like that:

``` c
Kalman myFilter(0.125, 40, 0, 400);
```

And then you try to change q (first parameter = process noise) and r (second parameter = sensor noise) to meet your sensor and process characteristics.
Maybe you can read the reference http://interactive-matter.eu/blog/2009/12/18/filtering-sensor-data-with-a-kalman-filter/ to learn more about regulating the filter parameters and also about the filtering process itself.
Regards,

**Comment by timur01061984** [comment]
Thank you. Problem was solved.
