### ISSUE TITLE
Filter frequency

### ISSUE THREAD

**Issue by Unzro** [bachagas/Kalman#2]
Hi, i'm using your library, and it works quite well in smoothing data from a touchscreen, really much better than other arduino Lowpass filter library, the problem is that after applying the filter, moving an object on touchscreen, data change very slowly, without reactivity. I thought is due to the frequency of the filter that can't be set.  I tried to open Lowpass library(where frequency can be regulated), to modify your code, but seems quite difficult. Have you any suggestion? Thx in advance

**Comment by bachagas** [comment]
Hi,
I am sorry for the delay... It's been some time since the last time I played with it, but from what I could  remember, you need to find the appropriate values for the parameters when you create the filter:
```c
Kalman myFilter(0.125,32,1023,0); //suggested initial values for high noise filtering
```
If the first two parameters are too high, it will filter too much and you lose responsiveness.
I remember I plotted the input and the filtered input and tested until I found a good output.
The method:
```c
myFilter.setParameters(double process_noise, double sensor_noise, double estimated_error)
```
may be useful for making these tests.
You should also read the link from where I took the original implementation: http://interactive-matter.eu/blog/2009/12/18/filtering-sensor-data-with-a-kalman-filter/
Maybe you get some insights from there too.
Hope that helps!
